// <auto-generated />
using System;
using DesafioBackendSprint3_GabrielVinicius.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioBackendSprint3_GabrielVinicius.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513192011_AdicionarTabelaTransacoes")]
    partial class AdicionarTabelaTransacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DesafioBackendSprint3_GabrielVinicius.Models.ContaBancaria", b =>
                {
                    b.Property<int>("NumeroConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NumeroConta"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("NumeroConta");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ContasBancarias");

                    b.HasDiscriminator().HasValue("ContaBancaria");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DesafioBackendSprint3_GabrielVinicius.Models.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaBancariaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("DesafioBackendSprint3_GabrielVinicius.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DesafioBackendSprint3_GabrielVinicius.Models.ContaCorrente", b =>
                {
                    b.HasBaseType("DesafioBackendSprint3_GabrielVinicius.Models.ContaBancaria");

                    b.HasDiscriminator().HasValue("ContaCorrente");
                });

            modelBuilder.Entity("DesafioBackendSprint3_GabrielVinicius.Models.ContaEmpresarial", b =>
                {
                    b.HasBaseType("DesafioBackendSprint3_GabrielVinicius.Models.ContaBancaria");

                    b.Property<decimal>("LimiteEmprestimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("LimiteEmprestimoEmUso")
                        .HasColumnType("decimal(65,30)");

                    b.HasDiscriminator().HasValue("ContaEmpresarial");
                });

            modelBuilder.Entity("DesafioBackendSprint3_GabrielVinicius.Models.ContaPoupanca", b =>
                {
                    b.HasBaseType("DesafioBackendSprint3_GabrielVinicius.Models.ContaBancaria");

                    b.HasDiscriminator().HasValue("ContaPoupanca");
                });

            modelBuilder.Entity("DesafioBackendSprint3_GabrielVinicius.Models.ContaBancaria", b =>
                {
                    b.HasOne("DesafioBackendSprint3_GabrielVinicius.Models.Usuario", "Usuario")
                        .WithMany("Contas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DesafioBackendSprint3_GabrielVinicius.Models.Transacao", b =>
                {
                    b.HasOne("DesafioBackendSprint3_GabrielVinicius.Models.ContaBancaria", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("DesafioBackendSprint3_GabrielVinicius.Models.Usuario", b =>
                {
                    b.Navigation("Contas");
                });
#pragma warning restore 612, 618
        }
    }
}
